# Generated by Django 4.2.9 on 2024-02-07 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        ),
    ]
